name: Check Markdown links

on:
  workflow_dispatch:
  schedule:
  # Every Monday at 1p UTC https://crontab.guru/#0_13_*_*_1
  - cron: "0 13 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
